dist: trusty
sudo: required
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    secure: OS2t2tnwZWittCK1C5XpQv41k5zVljZPAmG8DEY1D37RemkyKcNxaXeZwa1/y7qsJZCnPZE4wGbjSE3O3RTbtHbTfb7fBfy3NO/OWjOxszFayS21780U7BSnO9W76FpRyOXZyslsN16gd3Re5FRPvYEJ8w8JvuxhecVpZ6bUUhs+t7i31iQQIpbkat6SN3MmIO+Sb69osP/N4J+dRE40Kiowyp+6pNTlww0cy/uz87R1hnOyy5Izymp2IVAoiR+nAFx6c0Z5l9nYBh5tACQ+2HH+JRuGXndvJatHQeBKw2Ewxxl+NfpG6IGv+Wd5PDnnlotP4ZHUYicx03XjGDuZWiwK01nIn11HhC7UA1ptVvlENXDXWY2EiiXVJgOtNxP+PH5BRivjUEgTBzqS9HQ5fB9HWVQeI4yTN92eN8w/dywek05PYBk04HjjnIYusvnJjzisNjeWQlD8tiQs1oMhsHJO9km1a9TW4/xaD9HDPof2UNaZDEhkXIxRNPtOKQnFajTqA4MWHIr9q8qruXAeRvhcx8gPk06JxatlN/wbQN0EictnZNQbhvCRs9j33Vk7PKNVquths61YYx2nFMKBGT3iHn4HP7Z5iHmfpkYdYdw9SROsLbxR0uxzk8hwQ/cFwEWc6cky25gZu5u8bJu3iIZo+nzcWvjkTsBVcIawlyk=
node_js:
- '7'
branches:
  only:
  - master
  - dev
before_install:
- rm -rf node_modules
before_script:
- npm prune
- yarn run post-install
- yarn run lint
script:
- yarn run dist
env:
  global:
  - ENCRYPTION_LABEL: d9215e5535f8
  - COMMIT_AUTHOR_EMAIL: travis@hcuge.ch
before_deploy:
- cd dist
deploy:
  provider: npm
  email: gmer@hcuge.ch
  skip_cleanup: true
  api_key:
    secure: jZGmu5/zacHZFaVSoNyRnxYeXWO6Mi9xqZXcwsBGs5pwQXLe+G6SlRu47TjcGWH+R6iOWEwOMSNqYqAD+j1ZCbR8yRTI2M1ijvJPBjLnxA1GxPBeQ0TnTC/unFsAjap6c0fgXlzQFaervxNkwUCdBfZc1B3PscQrSC3Yaaxdb48U17HTgzZi80a/cn2Y8ulOYKMfm3kpJ5GA36XS56ANaeSEpiUELckpvCSmXkn4ukofwkJ0UdadMLcjtFsesmfZA1HanxuHZsTrTXkGKsN+GwKzrV+9ZkNJgj3KsbdBTu4FBA4OJ2eNOsQVnBUMla3FWN09/Sw4Acdz9m53nDQ2kJoqFjIKZzAZGT2DXH+YcLTR7HSEReUo6+TPRb+uKl4ONB6HBdFHeVG+Btg7ml/y7qeMXga/MwsrS3L01UuKqgprO/DdYl3ShHgv6TdScd/Yzm0CoT23PXHLy0iAFi0rR/8xFA1GX0XLfXGrbFU81NYVrqKKnxy9rn0xxMuMY7k59iZ5akqRJcFCHB1lsGCmMn/AJcSdDinDTMhF5QmzkvMWDoTv8FYucfCMVQSM5RSW1zuWaGVnw5D4EYVapBA3NCb17vjGS9e5Hkp5lNiDzM6a46uMhgzse+yW7+pudfLJbi0y/TN3iRhkF289dKXs0VO4vwpPHHDyCNxeuqUmOLk=
  on:
    repo: DSI-HUG/json-object-mapper
    branch: master
after_deploy:
- cd ..
- bash ./tools/scripts/tag.sh
